### ISSUE TITLE
Issue with Set Hyperparameters

### ISSUE THREAD

**Issue by yueyaog** [lujonathanh/BETS#1]
Hi Jonathan,

I read your great paper and I am very interested to try BETS on my own time_series RNA-Seq datasets. I am following the BETS_tutorial.md and I met some trouble under the Running BETS, 1. Set hyperparameters. "Set the list of scripts to run from. export scriptlist=cv_parallel_script_list.txt" I couldn't locate "cv_parallel_script_list.txt" anywhere. Did you forgot to post it or it required some other things which I didn't know?

Thanks,
Gao

**Comment by lujonathanh** [comment]
Hi Gao,

Thanks for using this software! Sorry for the lack of clarity. 

You first have to run the steps under "Preparing for a Run"

cv_parallel_script_list.txt is a file created by running the sequence of commands, specifically "./prep_jobs_rand_cv.sh"
